### ISSUE TITLE
Package deleted: https://github.com/dunglas/vulcain/caddy

### ISSUE THREAD

**Issue by digitaltim-de** [dunglas/vulcain#100]
My Symfony Docker Vulcain Installation failed, because this package is disabled or deleted? Why?

**Comment by dunglas** [comment]
It still exists: https://github.com/dunglas/vulcain/blob/main/caddy/go.mod

**Comment by ziedAlmia7** [comment]
I'm also having a problem with symfony docker installation : 
the error seems to come from these files : 
#0 162.2 # github.com/dunglas/vulcain
#0 162.2 /go/pkg/mod/github.com/dunglas/vulcain@v0.4.0/openapi.go:16:20: undefined: openapi3.Swagger
#0 162.2 /go/pkg/mod/github.com/dunglas/vulcain@v0.4.0/openapi.go:23:27: undefined: openapi3.NewSwaggerLoader

**Comment by digitaltim-de** [comment]
> I'm also having a problem with symfony docker installation : 
> 
> the error seems to come from these files : 
> 
> #0 162.2 # github.com/dunglas/vulcain
> 
> #0 162.2 /go/pkg/mod/github.com/dunglas/vulcain@v0.4.0/openapi.go:16:20: undefined: openapi3.Swagger
> 
> #0 162.2 /go/pkg/mod/github.com/dunglas/vulcain@v0.4.0/openapi.go:23:27: undefined: openapi3.NewSwaggerLoader

 I hve the same error

**Comment by silviuvoicu** [comment]
From a docker-compose :

[INFO] exec (timeout=0s): /usr/local/go/bin/go get -d -v github.com/dunglas/vulcain github.com/caddyserver/caddy/v2@v2.6.2 
#54 162.6 go: downloading github.com/dunglas/vulcain v0.4.1
#54 162.8 go: github.com/dunglas/vulcain@v0.4.1: verifying module: github.com/dunglas/vulcain@v0.4.1: reading https://sum.golang.org/lookup/github.com/dunglas/vulcain@v0.4.1: 404 Not Found
#54 162.8       server response: not found: github.com/dunglas/vulcain@v0.4.1: invalid version: unknown revision v0.4.1
#54 162.8 2023/01/14 09:08:15 [FATAL] exit status 1

**Comment by dunglas** [comment]
We just released this version (0.4.1): https://pkg.go.dev/github.com/dunglas/vulcain?tab=versions

Maybe wait for this release to propagate?

**Comment by back-2-95** [comment]
Worked for me (0.4.1)
