### ISSUE TITLE
Regression since 0.4.1

### ISSUE THREAD

**Issue by bpolaszek** [dunglas/vulcain#102]
Hello,

I upgraded Caddy on my staging env yesterday (using xcaddy `--with github.com/dunglas/vulcain/caddy`) and observed that responses from unchanged requests are now broken.

Request (basically, fetch + preload all IRIs of an Hydra Collection):

```http
GET /api/books
fields: "@type", "/hydra:member/*/@id", "/hydra:totalItems"
preload: "/hydra:member/*/@id"
```

Produced  (using `v0.0.0-20220906084821-705c1113298e` built on Sept 27, 2022):
```json
{
  "hydra:member": [
    {
      "@id": "\/api\/books\/01FT5VZY5HPGXGTJFMERMZ8E01"
    }
  ],
  "@type": "hydra:Collection",
  "hydra:totalItems": 1
}
```

Now(`v0.4.1`):
```json
{
  "hydra:member": [
    {}
  ],
  "hydra:totalItems": 1
}
```

Did something changed I'm not aware of? I couldn't find any info in the changelog nor in the documentation. 
At first glance it just looks like Vulcain doesn't like `@` properties anymore.

Thanks,
Ben

**Comment by dunglas** [comment]
Could you check which version of sjson you use? This looks similar to https://github.com/tidwall/sjson/issues/66

**Comment by bpolaszek** [comment]
```bash
./caddy list-modules --versions | grep sjson
```

returns nothing - where am I supposed to find that information?

**Comment by dunglas** [comment]
In your `go.sum` file.
