### ISSUE TITLE
Cannot tag Vulcain in Stackoverflow

### ISSUE THREAD

**Issue by JeremyPasco** [dunglas/vulcain#110]
Just to mention, as stated in `/doc/hepl.md`, requiring help should be done through Stackoverflow with the use of `vulcain` tag. Sadly, this tag has never been created there and only users with 15k+ reputation can.
I don't have enough reputation to tag my questions with it. Could you please create it?

**Comment by dunglas** [comment]
Unfortunately, I don't have enough reputation either. Perhaps we could use the "api-platform.com" tag in the meantime, as the two projects are closely related?

**Comment by JeremyPasco** [comment]
Ok! here is the PR: #128
