### ISSUE TITLE
Is it ok to use the name "Vulcain" in an alternative implementation of the protocol?

### ISSUE THREAD

**Issue by trieloff** [dunglas/vulcain#27]
I am working on a (WIP) implementation of parts of the Vulcain protocol to be used in a server less (OpenWhisk) environment here: https://github.com/trieloff/helix-vulcain-filters

Is it ok to use the term "Vulcain" in the project name?

**Comment by webdevium** [comment]
Same question. But I select [vulcainode](https://github.com/webdevium/vulcainode)

**Comment by dunglas** [comment]
Wow, it makes me supper happy to already such implementations! Thanks!
And it's perfectly ok to use "vulcain" in the project name. We should also add your projects to the docs.

**Comment by trieloff** [comment]
Thanks, I will create a PR with a link once the project is in the final location.
