### ISSUE TITLE
Will 'object' remain a permanent key for targeting nested content ?

### ISSUE THREAD

**Issue by edimitchel** [dunglas/vulcain#28]
Hi Dunglas,

I see examples and I have to say that the object attribute is a little weird for me..

This key name is coming for your conception or from another architecture?

IMHO, I'll prefer to use a key name named like `content` or `value` or more specific to Vulca(i)n `outbreak` or `rash`.

Thanks for reading !

**Comment by dunglas** [comment]
There is no `object` attribute in the spec itself. `object` appears in the example just because the `activity` type of the Mastodon API (that we use for the example) as an `object` property. But it's not related to Vulcain at all.
