### ISSUE TITLE
Link to IETF

### ISSUE THREAD

**Issue by laurent35240** [dunglas/vulcain#30]
Hi,

I noticed that the link to IETF page (https://datatracker.ietf.org/doc/draft-dunglas-vulcain/) from README page is not working.
I tried to find correct link on IETF website but could not find it.

Is it because the request for this new standard is not registered yet by IETF?

Laurent

**Comment by dunglas** [comment]
I've not submitted the draft yet, but I'll do it soon.

**Comment by Agares** [comment]
👋 hey, any progress on getting this submitted?

**Comment by dunglas** [comment]
It is now online! https://datatracker.ietf.org/doc/draft-dunglas-vulcain/
