### ISSUE TITLE
Why is it AGPL licensed?

### ISSUE THREAD

**Issue by gabel** [dunglas/vulcain#31]
While AGPL is a valid license, it might be blocking the usage of Vulcain in enterprise environments (legal considerations). Is there any reason to not publish it under an even more less restrictive license as MIT?

**Comment by gabel** [comment]
I guess the reason is stated in https://twitter.com/dunglas/status/1182886985540755456

> Basically the goal of using AGPL here  is to force the redistribution of changes made to the Gateway Server itself. The backend behind the servers don’t have to be redistributed.
The protocol itself will be published under the 
@ietf
 license (permissive) https://rfc-editor.org/faq/

But I still assume the license will lower the adoption rate.

**Comment by dunglas** [comment]
I discussed this more in depths on Hacker News: https://news.ycombinator.com/item?id=21240715

AGPL shouldn't be an issue for almost all companies (except, maybe, Cloud Providers, but that's the goal). But if it is for yours, drop me a mail with the specifics and I'll see what we can do!

Also, as stated on the homepage, the spec itself is free to implement by any software, even proprietary and commercial ones. Same for the Gateway server. AGPL only prevents to create a proprietary version of the gateway server itself without redistributing the modifications.

**Comment by gabel** [comment]
The docs made it almost clear thanks for giving more details on it. 

Some corporates are just very careful on GPL/AGPL dependencies to not risk any IP discussions... even though you just want to use it as is and not even change it. 

Closing here.
