### ISSUE TITLE
Official Docker Container 

### ISSUE THREAD

**Issue by thedrow** [dunglas/vulcain#51]
Please provide an official docker container for the gateway server.
It'd be much easier to deploy this way.

**Comment by thedrow** [comment]
I didn't notice you do have a Docker image.
Can we mention that in the README file directly?

**Comment by dunglas** [comment]
Yes I'll add it to the readme!

**Comment by dunglas** [comment]
Actually it's already documented: https://github.com/dunglas/vulcain/blob/2b9119cbfdfc469023d1d78cda263ff1833bd08d/docs/gateway/install.md#docker-image
