### ISSUE TITLE
Don't modify the response if the response is marked as no-transform

### ISSUE THREAD

**Issue by dunglas** [dunglas/vulcain#66]
See https://tools.ietf.org/html/rfc7234#section-5.2.2.4.
We should also send [a `Warning: 214` header](https://tools.ietf.org/html/rfc7234#section-5.5.6) when we rewrite the URLs or remove some fields.

**Comment by realsdx** [comment]
I would like to work on this issue

**Comment by dunglas** [comment]
@realsdx you're very welcome!

**Comment by realsdx** [comment]
@dunglas Thanks!
Can you give me a pointer on where should i start for this? I have a working development setup of the master. I am currently trying to understand the code base

**Comment by dunglas** [comment]
This should be handled here: https://github.com/dunglas/vulcain/blob/master/vulcain.go#L156

**Comment by realsdx** [comment]
@dunglas Should add the warning header when this `Apply` function https://github.com/dunglas/vulcain/blob/master/vulcain.go#L180 is called ?
And should i submit that  in separate PR ?
