### ISSUE TITLE
Clear up inconsistency in documentation of production-readiness of the Gateway Server

### ISSUE THREAD

**Issue by steef-paqt** [dunglas/vulcain#67]
While reading the documentation, I stumbled on this inconsistency in the documentation.

On the [readme.md](https://github.com/dunglas/vulcain/blob/master/README.md) it says:
> A reference, **production-grade**, implementation gateway server is also available in this repository.

While on the linked page ([Install The Gateway Server](https://github.com/dunglas/vulcain/blob/master/docs/gateway/install.md)), it says about the Gateway server:
> **The Gateway Server is still experimental**

So what is it? Either it is "experimental" or it is "production-grade". So one of these wordings should be changed.

Or it is somehow both, but some clarification on "why" would be in order in that case.

**Comment by dunglas** [comment]
Younes right. We have to clarify.

It is stable enough to be used in production (it will not crash, and behaves properly). But it's still a 0.x version, the spec itself and the configuration format of the server can still (and will) change often.
