### ISSUE TITLE
HTTP and HTTPS Vulcain server question

### ISSUE THREAD

**Issue by varloc2000** [dunglas/vulcain#71]
Good day!

The quote from [Gateway Server Configuration](https://github.com/dunglas/vulcain/blob/main/docs/gateway/config.md)

> If ACME_HOSTS or both CERT_FILE and KEY_FILE are provided, an HTTPS server supporting HTTP/2 connection will be started. If not, an HTTP server will be started (not compatible with HTTP/2 Server Push, and not secure).

From quote above I made assumption that HTTPS and HTTP servers can not work simultaneously. 

And here in an example of how to start vulcain using docker [Install The Gateway Server/Docker Image](https://github.com/dunglas/vulcain/blob/main/docs/gateway/install.md#docker-image)

```docker run \
    -e UPSTREAM='http://your-api' -e ACME_HOSTS='example.com' \
    -p 80:80 -p 443:443 \
    dunglas/vulcain
```

In example above, both - http (80) and https (443) ports are forwarded. Does that mean that both versions of server will run same time?

**Comment by dunglas** [comment]
Yes. And HTTP redirects to HTTPS.
