### ISSUE TITLE
Removal of Push support in Chrome

### ISSUE THREAD

**Issue by luchsamapparat** [dunglas/vulcain#72]
Sadly, it seems that Push-Support is being removed from Chrome.

https://evertpot.com/http-2-push-is-dead/

Any ideas what this means for this project?

**Comment by dunglas** [comment]
See https://github.com/dunglas/vulcain/issues/70.

To summarize, it's not that dramatic for the project. We're in the process of upgrading the documentation to explain how Vulcain works without Server Push.

**Comment by luchsamapparat** [comment]
Sorry, I must have missed that issue
